defaults: &defaults 
  host:     192.168.10.20
  username: root
  password: zhilu
  pool: 5
  timeout: 5000

mysql:
  adapter:  mysql2
  database: zl_mqtt
  <<: *defaults

slqite3:  
  adapter: sqlite3
  database: zl_mqtt.db
